# Generated by Django 3.1.7 on 2021-03-22 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='设备尺寸'),
        ),
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='技术描述'),
        ),
        migrations.AlterField(
            model_name='product',
            name='model',
            field=models.CharField(default='', max_length=128, verbose_name='型号'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='设备名称'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=50, verbose_name='面价'),
        ),
    ]
