# Generated by Django 3.1.7 on 2021-03-22 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210322_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='object_id',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='料号'),
        ),
    ]
