# Generated by Django 3.1.7 on 2021-03-22 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0003_product_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='create_by',
            field=models.ForeignKey(default=orders.models.setDefaultUser, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='order_creator', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='order',
            name='update_by',
            field=models.ForeignKey(default=orders.models.setDefaultUser, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='order_updater', to=settings.AUTH_USER_MODEL, verbose_name='更新人'),
        ),
    ]
