# Generated by Django 3.1.7 on 2021-03-22 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20210322_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_quantity',
            field=models.SmallIntegerField(default=0, verbose_name='订单总数量'),
        ),
    ]
