# Generated by Django 3.1.7 on 2021-03-24 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_total_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='quantity',
        ),
        migrations.AddField(
            model_name='cart',
            name='item_quantity',
            field=models.SmallIntegerField(default=0, verbose_name='产品种类数量'),
        ),
    ]
